
include:
  - remote: "https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/PreCommit.gitlab-ci.yml"
  - remote: "https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/ArtifactoryPyPI.gitlab-ci.yml"
  - remote: "https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/SonarScanner.gitlab-ci.yml"

variables:
  CC: "mpicc"
  CXX: "mpic++"

run-tests:
  tags:
    - docker
  stage: test
  image: continuumio/miniconda3:23.5.2-0
  before_script:
    - conda install -c conda-forge gcc gxx fftw mpich pytest pytest-cov coverage numpy scipy matplotlib
    - python setup.py clean
    - pip install .
  script:
    - pytest tests --junitxml=junit.xml --cov-report xml --cov-report term --cov orbit
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - junit.xml
      - coverage.xml
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build-pypi-package-py310:
  extends: build-pypi-package
  image: conda/miniconda3-centos7:latest
  before_script:
    - yum install -y gcc gcc-c++
    - conda update -y -n base -c defaults conda
    - conda create -y -n python310 python=3.10
    - conda init bash
    - source ~/.bashrc
    - conda activate python310
    - conda install -y -c conda-forge git fftw mpich mpich-mpicc mpich-mpicxx

build-pypi-package:
  image: conda/miniconda3-centos7:latest
  before_script:
    - yum install -y gcc gcc-c++
    - conda update -y -n base -c defaults conda
    - conda create -y -n python311 python=3.11
    - conda init bash
    - source ~/.bashrc
    - conda activate python311
    - conda install -y -c conda-forge git fftw mpich mpich-mpicc mpich-mpicxx
